[update to 0.9.0] Move import of ABCs from collections into version-specific part of _compat module.
Achim Herwig (1):
      Move import of ABCs from collections into version-specific part of _compat module.

Ahmed Haque (1):
      Update pool.py

Ian Cordasco (1):
      Fix URL for the project after the move

Ian Stapleton Cordasco (1):
      Remove py33 from testing

Ivo Rothschild (2):
      Added fix for OSX TCPKeepAliveAdapter.
      Use socket.TCP_KEEPALIVE if set on OSX in TCPKeepAliveAdapter.

Jonathan Hawes (1):
      Coerce proxy URL to bytes before dumping request

Krystian Różycki (14):
      Stateless solution for streaming files by multipart from one host to another
      TYPO
      TYPO 2
      pull-request changes - stage I
      pull-request changes - stage Ib
      pull-request changes - adding examples to class doc
      import fix in doc
      tests for FileFromURLWrapper
      ValueError: negative count - on my local machine for p3.5 (checking with travis)
      fix for 'negative count' issue in p35
      default chunk_size changed to 8090
      workaround for '*** ValueError: negative count'
      fix for older version of requests
      updating file_for_download.json

Ryan (1):
      Add X509 Adapter that can handle PKCS12

Ryan Ashley (2):
      Update history to reflect commits since 0.8.0
      Revised as requested

StKob (1):
      Updating link to example

Steven Maude (1):
      Fix "oject" to "object" in MultipartEncoder

Thomas Hauk (3):
      Fix bug when MultipartEncoder is asked to encode zero parts
      Add newline to end of file
      Add myself to AUTHORS.rst

Victor (1):
      Fix typos in MultipartDecoder docstring

Yorgos Pagles (1):
      Correct the type of non string request body dumps

Yury V. Zaytsev (1):
      Avoid bailing out with exception upon empty response reason

david (2):
      Fix callback signature in docs to match the code. Closes #223
      Rename the argument to make it clear that the received object is a monitor instance

kefevs (1):
      Fix bug/199, enabling support for contenttype with capital letters.

tzickel (1):
      Removed content from being stored in MultipartDecoder

yuuuker (1):
      fix parentheses match in example usage